In [1]:
import pandas as pd

new_SLMS = pd.read_csv('C:/Users/jiahu_000/Desktop/CIBC/Check Duplicates Table Names/new_SLMS_schema.csv', header=None)

existing_SLMS = pd.read_csv('C:/Users/jiahu_000/Desktop/CIBC/Check Duplicates Table Names/existing_SLMS_schema.csv', header=None)

new_existing_SLMS = pd.read_csv('C:/Users/jiahu_000/Desktop/CIBC/Check Duplicates Table Names/new_and_existing_SLMS_schema.csv', header=0)

In [2]:
new_SLMS

                               0
0                  ADM_APP_ERROR
1              ADM_BUSINESS_UNIT
2             ADM_EMERGENCY_LOGS
3                    ADM_PROFILE
4                      ADM_RIGHT
..                           ...
251           ST_CTX_CONTEXT_HIT
252             FIRCO_CTY_REPORT
253    FIRCO_CTY_REPORT_TEMPLATE
254        FIRCO_CTY_REPORT_UNIT
255  FIRCO_CTY_REF_TEMPLATE_FILE

[256 rows x 1 columns]

In [3]:
existing_SLMS

                                0
0                     FOFA_ACTION
1                FOFA_HIST_ACTION
2                   FIRCO_APP_LOG
3    FIRCO_CTY_STRIPPING_CHECKSUM
4                FOF_AUDIT_SYSTEM
..                            ...
123        FOFA_HIST_INTERVENTION
124                 FOF_HIST_HITS
125                  FOFA_MESSAGE
126             FOFA_INTERVENTION
127                      FOF_HITS

[128 rows x 1 columns]

In [4]:
new_existing_SLMS

     Category              Table Name
0         new           ADM_APP_ERROR
1         new       ADM_BUSINESS_UNIT
2         new      ADM_EMERGENCY_LOGS
3         new             ADM_PROFILE
4         new               ADM_RIGHT
..        ...                     ...
379  existing  FOFA_HIST_INTERVENTION
380  existing           FOF_HIST_HITS
381  existing            FOFA_MESSAGE
382  existing       FOFA_INTERVENTION
383  existing                FOF_HITS

[384 rows x 2 columns]

In [5]:
df = pd.concat([new_SLMS, existing_SLMS], ignore_index=True)
df

                          0
0             ADM_APP_ERROR
1         ADM_BUSINESS_UNIT
2        ADM_EMERGENCY_LOGS
3               ADM_PROFILE
4                 ADM_RIGHT
..                      ...
379  FOFA_HIST_INTERVENTION
380           FOF_HIST_HITS
381            FOFA_MESSAGE
382       FOFA_INTERVENTION
383                FOF_HITS

[384 rows x 1 columns]

In [6]:
df.duplicated(keep='last').sum()

37

In [7]:
df.loc[df.duplicated(keep='last'), :].sort_values(by=0)

                                  0
8                        CODE_TYPES
43                    FIRCO_APP_LOG
180   FIRCO_CTY_BU_SANCTION_CONFIGS
46                   FIRCO_CTY_LIST
47            FIRCO_CTY_LIST_RECORD
48       FIRCO_CTY_ORIGINAL_MESSAGE
49                FIRCO_CTY_PAIRING
50   FIRCO_CTY_PAIRING_HIST_MESSAGE
51        FIRCO_CTY_PAIRING_MESSAGE
52           FIRCO_CTY_PAIRING_RULE
53           FIRCO_CTY_Q_DESCRIPTOR
255     FIRCO_CTY_REF_TEMPLATE_FILE
252                FIRCO_CTY_REPORT
54             FIRCO_CTY_REPORT_JOB
55        FIRCO_CTY_REPORT_JOB_UNIT
253       FIRCO_CTY_REPORT_TEMPLATE
254           FIRCO_CTY_REPORT_UNIT
56         FIRCO_CTY_SANCTION_LISTS
57    FIRCO_CTY_SCHEDULED_EXECUTION
58   FIRCO_FIN_DAILY_RECONCILIATION
59         FIRCO_FIN_EXCEPTION_LIST
60                FIRCO_FIN_MESSAGE
62        FIRCO_FIN_MESSAGE_CAT_SET
63           FIRCO_FIN_MESSAGE_TYPE
64        FIRCO_FIN_MESSAGE_TYPE_BU
65                 FIRCO_FIN_STATUS
66   FIRCO_WKF_APPLICATION_LICENSES
67            FIRCO_WKF_DB_VERSIONS
68                 FKTA_D_COMMIT_ID
69              FMF_COMMENT_CLASSES
70                    FMF_DECSIGNAT
71               FMF_LOGIN_FAILURES
72               FMF_MAIL_TEMPLATES
115                          SEARCH
184               SEARCH_ATTRIBUTES
185                    SEARCH_CODES
116                    SEARCH_NAMES

In [8]:
new_existing_SLMS.duplicated(subset=['Table Name'], keep='last').sum()

37

In [9]:
new_existing_SLMS.loc[new_existing_SLMS.duplicated(subset=['Table Name'], keep='last'), :].sort_values(by='Table Name')

    Category                      Table Name
8        new                      CODE_TYPES
43       new                   FIRCO_APP_LOG
180      new   FIRCO_CTY_BU_SANCTION_CONFIGS
46       new                  FIRCO_CTY_LIST
47       new           FIRCO_CTY_LIST_RECORD
48       new      FIRCO_CTY_ORIGINAL_MESSAGE
49       new               FIRCO_CTY_PAIRING
50       new  FIRCO_CTY_PAIRING_HIST_MESSAGE
51       new       FIRCO_CTY_PAIRING_MESSAGE
52       new          FIRCO_CTY_PAIRING_RULE
53       new          FIRCO_CTY_Q_DESCRIPTOR
255      new     FIRCO_CTY_REF_TEMPLATE_FILE
252      new                FIRCO_CTY_REPORT
54       new            FIRCO_CTY_REPORT_JOB
55       new       FIRCO_CTY_REPORT_JOB_UNIT
253      new       FIRCO_CTY_REPORT_TEMPLATE
254      new           FIRCO_CTY_REPORT_UNIT
56       new        FIRCO_CTY_SANCTION_LISTS
57       new   FIRCO_CTY_SCHEDULED_EXECUTION
58       new  FIRCO_FIN_DAILY_RECONCILIATION
59       new        FIRCO_FIN_EXCEPTION_LIST
60       new               FIRCO_FIN_MESSAGE
62       new       FIRCO_FIN_MESSAGE_CAT_SET
63       new          FIRCO_FIN_MESSAGE_TYPE
64       new       FIRCO_FIN_MESSAGE_TYPE_BU
65       new                FIRCO_FIN_STATUS
66       new  FIRCO_WKF_APPLICATION_LICENSES
67       new           FIRCO_WKF_DB_VERSIONS
68       new                FKTA_D_COMMIT_ID
69       new             FMF_COMMENT_CLASSES
70       new                   FMF_DECSIGNAT
71       new              FMF_LOGIN_FAILURES
72       new              FMF_MAIL_TEMPLATES
115      new                          SEARCH
184      new               SEARCH_ATTRIBUTES
185      new                    SEARCH_CODES
116      new                    SEARCH_NAMES

In [10]:
new_existing_SLMS.loc[new_existing_SLMS.duplicated(subset=['Table Name'], keep='first'), :].sort_values(by='Table Name')

     Category                      Table Name
311  existing                      CODE_TYPES
258  existing                   FIRCO_APP_LOG
272  existing   FIRCO_CTY_BU_SANCTION_CONFIGS
286  existing                  FIRCO_CTY_LIST
287  existing           FIRCO_CTY_LIST_RECORD
364  existing      FIRCO_CTY_ORIGINAL_MESSAGE
320  existing               FIRCO_CTY_PAIRING
337  existing  FIRCO_CTY_PAIRING_HIST_MESSAGE
353  existing       FIRCO_CTY_PAIRING_MESSAGE
365  existing          FIRCO_CTY_PAIRING_RULE
288  existing          FIRCO_CTY_Q_DESCRIPTOR
372  existing     FIRCO_CTY_REF_TEMPLATE_FILE
377  existing                FIRCO_CTY_REPORT
309  existing            FIRCO_CTY_REPORT_JOB
348  existing       FIRCO_CTY_REPORT_JOB_UNIT
296  existing       FIRCO_CTY_REPORT_TEMPLATE
266  existing           FIRCO_CTY_REPORT_UNIT
338  existing        FIRCO_CTY_SANCTION_LISTS
270  existing   FIRCO_CTY_SCHEDULED_EXECUTION
339  existing  FIRCO_FIN_DAILY_RECONCILIATION
356  existing        FIRCO_FIN_EXCEPTION_LIST
274  existing               FIRCO_FIN_MESSAGE
328  existing       FIRCO_FIN_MESSAGE_CAT_SET
332  existing          FIRCO_FIN_MESSAGE_TYPE
291  existing       FIRCO_FIN_MESSAGE_TYPE_BU
306  existing                FIRCO_FIN_STATUS
297  existing  FIRCO_WKF_APPLICATION_LICENSES
295  existing           FIRCO_WKF_DB_VERSIONS
340  existing                FKTA_D_COMMIT_ID
329  existing             FMF_COMMENT_CLASSES
275  existing                   FMF_DECSIGNAT
276  existing              FMF_LOGIN_FAILURES
369  existing              FMF_MAIL_TEMPLATES
271  existing                          SEARCH
289  existing               SEARCH_ATTRIBUTES
301  existing                    SEARCH_CODES
318  existing                    SEARCH_NAMES